# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cylc_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsontracker',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
